name: build-storybook

on:
  push:
    branches:
      - develop
      - master

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Cache Node - npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-cache-

      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build Storybook
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build-storybook

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: storybook-files
          path: storybook-static

  deploy-storybook:
    runs-on: ubuntu-latest
    needs: build-storybook
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: storybook-files
          path: storybook-static

      - if: github.ref == 'refs/heads/master'
        name: Clear master folders
        run: |
          shopt -s extglob
          rm -rf -- !(develop|storybook-static|CNAME)
          mv storybook-static/* .

      - if: github.ref != 'refs/heads/master'
        name: Clear ${GITHUB_REF##*/} folders
        run: |
          rm -rf ${GITHUB_REF##*/}
          mv storybook-static ${GITHUB_REF##*/}

      - name: Commit updates
        run: |
          git add .
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git commit -m "Deploy storybook for ${GITHUB_REF##*/}."
          git pull --no-edit --quiet
          git push origin gh-pages
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
